name: karcisin_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_map: ^6.1.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  geolocator: ^10.1.0
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  http: ^1.6.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  latlong2: ^0.9.0
  midtrans_sdk: ^1.2.0
  path_provider: ^2.1.2
  pretty_dio_logger: ^1.3.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
